#!/bin/bash

set -e -u -x

cd $(dirname $0)/

dest=${1:-$PWD/bin}
mkdir -p $dest
export PATH=$dest:$PATH

curl -sSL https://github.com/moby/buildkit/releases/download/v0.10.0-rc2/buildkit-v0.10.0-rc2.linux-amd64.tar.gz \
  | tar -xzvf - -C $dest --strip-components=1
buildkitd --version
buildctl --version

curl -sSL https://github.com/rootless-containers/rootlesskit/releases/download/v0.14.6/rootlesskit-x86_64.tar.gz \
  | tar -xzvf - -C $dest
rootlesskit --version

curl -sSL https://github.com/opencontainers/runc/releases/download/v1.1.0/runc.amd64 \
  -o $dest/runc
chmod +x $dest/runc
runc --version
