#!/bin/bash

set -e -u

cd $(dirname $0)/

echo "starting buildkitd..." >&2

function msudo() {
  if [ "$(id -u)" != "0" ]; then
    sudo "$@"
  else
    "$@"
  fi
}

msudo mkdir -p /run/buildkit

if [ "$(id -u)" != "0" ]; then
  # choose first group arbitrarily
  group=$(groups | awk '{print $1}')
  msudo chown root:${group} /run/buildkit
  groupflag="--group ${group}"
else
  groupflag=""
fi

pidfile=/run/buildkit/buildkit.pid
msudo env "PATH=$PATH" start-stop-daemon \
  --start \
  --oknodo \
  --pidfile $pidfile \
  --make-pidfile \
  --background \
  ${groupflag} \
  --exec $PWD/buildkitd-log \
  -- --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
