#!/bin/bash

set -e -u

cd $(dirname $0)/

[ -d $PWD/bin ] && export PATH=$PWD/bin:$PATH

echo "starting buildkitd..." >&2

# choose first group arbitrarily
group=$(groups | awk '{print $1}')

sudo mkdir -p /run/buildkit
sudo chown root:${group} /run/buildkit

pidfile=/run/buildkit/buildkit.pid
sudo start-stop-daemon \
  --start \
  --oknodo \
  --pidfile $pidfile \
  --make-pidfile \
  --background \
  --group ${group} \
  --exec $(which buildkitd) \
  -- --allow-insecure-entitlement security.insecure
