#!/bin/bash

set -e -u

cd $(dirname $0)/

[ -d $PWD/bin ] && export PATH=$PWD/bin:$PATH

echo "stopping buildkitd..." >&2

function msudo() {
  if [ "$(id -u)" != "0" ]; then
    sudo "$@"
  else
    "$@"
  fi
}

pidfile=/run/buildkit/buildkit.pid
msudo env "PATH=$PATH" start-stop-daemon \
  --stop \
  --oknodo \
  --pidfile $pidfile \
  --remove-pidfile \
  --exec $(which buildkitd)
