#!/bin/bash

set -e -u

cd $(dirname $0)/

[ -d $PWD/bin ] && export PATH=$PWD/bin:$PATH

echo "stopping buildkitd..." >&2

pidfile=/run/buildkit/buildkit.pid
sudo env "PATH=$PATH" start-stop-daemon \
  --stop \
  --oknodo \
  --pidfile $pidfile \
  --remove-pidfile \
  --exec $(which buildkitd)
