#!/bin/bash

set -e -u -x

if [ "$#" -lt 3 ]; then
  echo "usage: $0 <bad> <good> <command...>" >&2
  exit 1
fi

bad=${1}
good=${2}
shift 2

git bisect start
git bisect bad $bad
git bisect good $good
git bisect run "$@"
