#!/usr/bin/env bash

cd $(dirname $0)/..

if [ "$#" != "1" ]; then
  echo "usage: $0 <tag>" >&2
  exit 1
fi

tag="$1"

./bass/bump-buildkit -i mod=./go.mod -i tag="$1" | \
  bass --export | \
  tar -xf -

go mod tidy

sed -i -e 's/const Version = .*/const Version = "'$tag'"/g' \
  pkg/runtimes/util/buildkitd/buildkitd.go

sed -i -e 's/(def \*buildkit-version\* ".*")/(def *buildkit-version* "'$tag'")/g' \
  bass/bass.bass
