#!/usr/bin/env bash

cd $(dirname $0)/..

set -e -u -x

./bass/nixery https://github.com/vito/nixery master | \
  bass --export | \
  tar -xf - --to-stdout image.tar | \
  skopeo --insecure-policy copy docker-archive:/dev/stdin docker://basslang/nixery:latest
