#!/usr/bin/env bash

cd $(dirname $0)/..

if [ "$#" != "1" ]; then
  echo "usage: $0 <tag>" >&2
  exit 1
fi

tag="$1"

./bass/bump-buildkit -i mod=./go.mod -i tag="$1" | \
  bass --export | \
  tar -xf -

go mod tidy
