#!/usr/bin/env bash

cd $(dirname $0)/..

set -e -u -x

./bass/nixery https://code.tvl.fyi/depot.git:/tools/nixery.git canon | bass -e > /tmp/nixery.tar

skopeo --insecure-policy copy oci-archive:/tmp/nixery.tar docker://basslang/nixery:latest
