#!/bin/bash

if [ "$#" != 2 ]; then
  echo "usage: $0 <module> <path>" >&2
  exit 1
fi

module=$1
path=$(realpath $2)
localpath=./hack/goreplace/$(basename $path)

cd $(dirname $0)/..
ln -sf $path $localpath
echo "replace $module => $localpath" >> go.mod
