#!/bin/bash

set -e -u -x

cd $(dirname $0)/..

mkdir -p $PWD/bin
export PATH=$PWD/bin:$PATH

curl -sSL https://github.com/moby/buildkit/releases/download/v0.9.3/buildkit-v0.9.3.linux-amd64.tar.gz \
  | tar -xzf - -C $PWD/bin --strip-components=1
buildkitd --version

curl -sSL https://github.com/rootless-containers/rootlesskit/releases/download/v0.14.6/rootlesskit-x86_64.tar.gz \
  | tar -xzf - -C $PWD/bin
rootlesskit --version

curl -sSL https://github.com/opencontainers/runc/releases/download/v1.0.3/runc.amd64 \
  -o $PWD/bin/runc
chmod +x $PWD/bin/runc
runc --version

go build -o $PWD/bin ./cmd/...
bass --version
