#!/bin/bash

set -e -u

# choose first group arbitrarily
group=$(groups | awk '{print $1}')

sudo mkdir -p /run/buildkit
sudo chown root:${group} /run/buildkit

echo "starting buildkitd..." >&2

pidfile=/run/buildkit/buildkit.pid
sudo start-stop-daemon \
  --start \
  --oknodo \
  --pidfile $pidfile \
  --make-pidfile \
  --background \
  --group ${group} \
  --exec $(which buildkitd) \
  -- --allow-insecure-entitlement security.insecure
