#!/bin/bash

set -e -u

echo "stopping buildkitd..." >&2

pidfile=/run/buildkit/buildkit.pid
sudo start-stop-daemon \
  --stop \
  --oknodo \
  --pidfile $pidfile \
  --remove-pidfile \
  --exec $(which buildkitd)
