#!/bin/bash

set -e -u

$(dirname $0)/buildkit/start
trap "$(dirname $0)/buildkit/stop" EXIT

echo "waiting for buildkitd..." >&2
until buildctl debug workers >&2; do
  echo "waiting for buildkitd..." >&2
  sleep 0.5
done

# pre-build bass and pkg/runtimes/shim/bin/ for tests
pushd $(dirname $0)/..
  # NB: for some reason, without a 'make clean' here the LSP tests fail. spent
  # an evening trying to figure out why. giving up for now. :(
  #
  # checked with 'file' and 'ldd' that the shim and bass exes should have been
  # compatible. still failed.
  make clean
  make -j out/bass
  export PATH=$PWD/out:$PATH
popd

bass --version

"$@"
