#!/bin/bash

set -e -u

$(dirname $0)/buildkit/start
trap "$(dirname $0)/buildkit/stop" EXIT

echo "waiting for buildkitd..." >&2
until buildctl debug workers >&2; do
  echo "waiting for buildkitd..." >&2
  sleep 0.5
done

dest=$(go env GOPATH)/bin
make clean
make -j "DESTDIR=${dest}" install
export PATH="$PATH:${dest}"

bass --version

"$@"
