#!/bin/bash

set -e -u

$(dirname $0)/start-buildkitd
trap "$(dirname $0)/stop-buildkitd" EXIT

echo "waiting for buildkitd..." >&2
until buildctl debug workers >&2; do
  echo "waiting for buildkitd..." >&2
  sleep 0.5
done

"$@"
