#!/usr/bin/env bash

set -e -u -x

cd $(dirname $0)/..

export PATH=$(go env GOPATH)/bin:$PATH

go install github.com/vito/booklit/cmd/booklit

booklit -i ./lit/index.lit \
  --html-templates ./html \
  --plugin github.com/vito/bass/docs/go \
  "$@"
