#!/usr/bin/env bash

set -e -u -x

cd $(dirname $0)/..

./hack/buildkit/setup $PWD/bin
export PATH=$PWD/bin:$PATH

# prevent hanging
export BASS_SIMPLE_OUTPUT=1

go install ./cmd/bass

./hack/with-buildkitd ./ci/check $GITHUB_SHA
