#!/bin/bash

set -e -u

cd $(dirname $0)/..

# ensure clean run for docker runtime tests
docker system prune --all --force

go list ./... | \
  grep -v /lsp | \
  xargs go test -cover -coverprofile=cover.out --covermode=count

curl https://deepsource.io/cli | sh

./bin/deepsource report \
  --analyzer test-coverage \
  --key go \
  --value-file ./cover.out
