// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: bass.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*Value_Null
	//	*Value_Bool
	//	*Value_Int
	//	*Value_String_
	//	*Value_Secret
	//	*Value_Array
	//	*Value_Object
	//	*Value_Thunk
	//	*Value_CommandPath
	//	*Value_FilePath
	//	*Value_DirPath
	//	*Value_HostPath
	//	*Value_ThunkPath
	//	*Value_LogicalPath
	//	*Value_ThunkAddr
	//	*Value_CachePath
	Value isValue_Value `protobuf_oneof:"value"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{0}
}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Value) GetNull() *Null {
	if x, ok := x.GetValue().(*Value_Null); ok {
		return x.Null
	}
	return nil
}

func (x *Value) GetBool() *Bool {
	if x, ok := x.GetValue().(*Value_Bool); ok {
		return x.Bool
	}
	return nil
}

func (x *Value) GetInt() *Int {
	if x, ok := x.GetValue().(*Value_Int); ok {
		return x.Int
	}
	return nil
}

func (x *Value) GetString_() *String {
	if x, ok := x.GetValue().(*Value_String_); ok {
		return x.String_
	}
	return nil
}

func (x *Value) GetSecret() *Secret {
	if x, ok := x.GetValue().(*Value_Secret); ok {
		return x.Secret
	}
	return nil
}

func (x *Value) GetArray() *Array {
	if x, ok := x.GetValue().(*Value_Array); ok {
		return x.Array
	}
	return nil
}

func (x *Value) GetObject() *Object {
	if x, ok := x.GetValue().(*Value_Object); ok {
		return x.Object
	}
	return nil
}

func (x *Value) GetThunk() *Thunk {
	if x, ok := x.GetValue().(*Value_Thunk); ok {
		return x.Thunk
	}
	return nil
}

func (x *Value) GetCommandPath() *CommandPath {
	if x, ok := x.GetValue().(*Value_CommandPath); ok {
		return x.CommandPath
	}
	return nil
}

func (x *Value) GetFilePath() *FilePath {
	if x, ok := x.GetValue().(*Value_FilePath); ok {
		return x.FilePath
	}
	return nil
}

func (x *Value) GetDirPath() *DirPath {
	if x, ok := x.GetValue().(*Value_DirPath); ok {
		return x.DirPath
	}
	return nil
}

func (x *Value) GetHostPath() *HostPath {
	if x, ok := x.GetValue().(*Value_HostPath); ok {
		return x.HostPath
	}
	return nil
}

func (x *Value) GetThunkPath() *ThunkPath {
	if x, ok := x.GetValue().(*Value_ThunkPath); ok {
		return x.ThunkPath
	}
	return nil
}

func (x *Value) GetLogicalPath() *LogicalPath {
	if x, ok := x.GetValue().(*Value_LogicalPath); ok {
		return x.LogicalPath
	}
	return nil
}

func (x *Value) GetThunkAddr() *ThunkAddr {
	if x, ok := x.GetValue().(*Value_ThunkAddr); ok {
		return x.ThunkAddr
	}
	return nil
}

func (x *Value) GetCachePath() *CachePath {
	if x, ok := x.GetValue().(*Value_CachePath); ok {
		return x.CachePath
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_Null struct {
	Null *Null `protobuf:"bytes,1,opt,name=null,proto3,oneof"`
}

type Value_Bool struct {
	Bool *Bool `protobuf:"bytes,2,opt,name=bool,proto3,oneof"`
}

type Value_Int struct {
	Int *Int `protobuf:"bytes,3,opt,name=int,proto3,oneof"`
}

type Value_String_ struct {
	String_ *String `protobuf:"bytes,4,opt,name=string,proto3,oneof"`
}

type Value_Secret struct {
	Secret *Secret `protobuf:"bytes,5,opt,name=secret,proto3,oneof"`
}

type Value_Array struct {
	Array *Array `protobuf:"bytes,6,opt,name=array,proto3,oneof"`
}

type Value_Object struct {
	Object *Object `protobuf:"bytes,7,opt,name=object,proto3,oneof"`
}

type Value_Thunk struct {
	Thunk *Thunk `protobuf:"bytes,8,opt,name=thunk,proto3,oneof"`
}

type Value_CommandPath struct {
	CommandPath *CommandPath `protobuf:"bytes,9,opt,name=command_path,json=commandPath,proto3,oneof"`
}

type Value_FilePath struct {
	FilePath *FilePath `protobuf:"bytes,10,opt,name=file_path,json=filePath,proto3,oneof"`
}

type Value_DirPath struct {
	DirPath *DirPath `protobuf:"bytes,11,opt,name=dir_path,json=dirPath,proto3,oneof"`
}

type Value_HostPath struct {
	HostPath *HostPath `protobuf:"bytes,12,opt,name=host_path,json=hostPath,proto3,oneof"`
}

type Value_ThunkPath struct {
	ThunkPath *ThunkPath `protobuf:"bytes,13,opt,name=thunk_path,json=thunkPath,proto3,oneof"`
}

type Value_LogicalPath struct {
	LogicalPath *LogicalPath `protobuf:"bytes,14,opt,name=logical_path,json=logicalPath,proto3,oneof"`
}

type Value_ThunkAddr struct {
	ThunkAddr *ThunkAddr `protobuf:"bytes,15,opt,name=thunk_addr,json=thunkAddr,proto3,oneof"`
}

type Value_CachePath struct {
	CachePath *CachePath `protobuf:"bytes,16,opt,name=cache_path,json=cachePath,proto3,oneof"`
}

func (*Value_Null) isValue_Value() {}

func (*Value_Bool) isValue_Value() {}

func (*Value_Int) isValue_Value() {}

func (*Value_String_) isValue_Value() {}

func (*Value_Secret) isValue_Value() {}

func (*Value_Array) isValue_Value() {}

func (*Value_Object) isValue_Value() {}

func (*Value_Thunk) isValue_Value() {}

func (*Value_CommandPath) isValue_Value() {}

func (*Value_FilePath) isValue_Value() {}

func (*Value_DirPath) isValue_Value() {}

func (*Value_HostPath) isValue_Value() {}

func (*Value_ThunkPath) isValue_Value() {}

func (*Value_LogicalPath) isValue_Value() {}

func (*Value_ThunkAddr) isValue_Value() {}

func (*Value_CachePath) isValue_Value() {}

type Thunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image    *ThunkImage   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Insecure bool          `protobuf:"varint,2,opt,name=insecure,proto3" json:"insecure,omitempty"`
	Args     []*Value      `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Stdin    []*Value      `protobuf:"bytes,5,rep,name=stdin,proto3" json:"stdin,omitempty"`
	Env      []*Binding    `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty"`
	Dir      *ThunkDir     `protobuf:"bytes,7,opt,name=dir,proto3" json:"dir,omitempty"`
	Mounts   []*ThunkMount `protobuf:"bytes,8,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Labels   []*Binding    `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty"`
	Ports    []*ThunkPort  `protobuf:"bytes,10,rep,name=ports,proto3" json:"ports,omitempty"`
	Tls      *ThunkTLS     `protobuf:"bytes,11,opt,name=tls,proto3" json:"tls,omitempty"`
}

func (x *Thunk) Reset() {
	*x = Thunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Thunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thunk) ProtoMessage() {}

func (x *Thunk) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thunk.ProtoReflect.Descriptor instead.
func (*Thunk) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{1}
}

func (x *Thunk) GetImage() *ThunkImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Thunk) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *Thunk) GetArgs() []*Value {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Thunk) GetStdin() []*Value {
	if x != nil {
		return x.Stdin
	}
	return nil
}

func (x *Thunk) GetEnv() []*Binding {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Thunk) GetDir() *ThunkDir {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *Thunk) GetMounts() []*ThunkMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *Thunk) GetLabels() []*Binding {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Thunk) GetPorts() []*ThunkPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Thunk) GetTls() *ThunkTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

type ThunkAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thunk  *Thunk `protobuf:"bytes,1,opt,name=thunk,proto3" json:"thunk,omitempty"`
	Port   string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
}

func (x *ThunkAddr) Reset() {
	*x = ThunkAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThunkAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThunkAddr) ProtoMessage() {}

func (x *ThunkAddr) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThunkAddr.ProtoReflect.Descriptor instead.
func (*ThunkAddr) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{2}
}

func (x *ThunkAddr) GetThunk() *Thunk {
	if x != nil {
		return x.Thunk
	}
	return nil
}

func (x *ThunkAddr) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ThunkAddr) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ThunkPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ThunkPort) Reset() {
	*x = ThunkPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThunkPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThunkPort) ProtoMessage() {}

func (x *ThunkPort) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThunkPort.ProtoReflect.Descriptor instead.
func (*ThunkPort) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{3}
}

func (x *ThunkPort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ThunkPort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ThunkTLS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert *FilePath `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Key  *FilePath `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ThunkTLS) Reset() {
	*x = ThunkTLS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThunkTLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThunkTLS) ProtoMessage() {}

func (x *ThunkTLS) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThunkTLS.ProtoReflect.Descriptor instead.
func (*ThunkTLS) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{4}
}

func (x *ThunkTLS) GetCert() *FilePath {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *ThunkTLS) GetKey() *FilePath {
	if x != nil {
		return x.Key
	}
	return nil
}

type ThunkImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Image:
	//
	//	*ThunkImage_Ref
	//	*ThunkImage_Thunk
	//	*ThunkImage_Archive
	//	*ThunkImage_DockerBuild
	Image isThunkImage_Image `protobuf_oneof:"image"`
}

func (x *ThunkImage) Reset() {
	*x = ThunkImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThunkImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThunkImage) ProtoMessage() {}

func (x *ThunkImage) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThunkImage.ProtoReflect.Descriptor instead.
func (*ThunkImage) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{5}
}

func (m *ThunkImage) GetImage() isThunkImage_Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (x *ThunkImage) GetRef() *ImageRef {
	if x, ok := x.GetImage().(*ThunkImage_Ref); ok {
		return x.Ref
	}
	return nil
}

func (x *ThunkImage) GetThunk() *Thunk {
	if x, ok := x.GetImage().(*ThunkImage_Thunk); ok {
		return x.Thunk
	}
	return nil
}

func (x *ThunkImage) GetArchive() *ImageArchive {
	if x, ok := x.GetImage().(*ThunkImage_Archive); ok {
		return x.Archive
	}
	return nil
}

func (x *ThunkImage) GetDockerBuild() *ImageDockerBuild {
	if x, ok := x.GetImage().(*ThunkImage_DockerBuild); ok {
		return x.DockerBuild
	}
	return nil
}

type isThunkImage_Image interface {
	isThunkImage_Image()
}

type ThunkImage_Ref struct {
	Ref *ImageRef `protobuf:"bytes,1,opt,name=ref,proto3,oneof"`
}

type ThunkImage_Thunk struct {
	Thunk *Thunk `protobuf:"bytes,2,opt,name=thunk,proto3,oneof"`
}

type ThunkImage_Archive struct {
	Archive *ImageArchive `protobuf:"bytes,3,opt,name=archive,proto3,oneof"`
}

type ThunkImage_DockerBuild struct {
	DockerBuild *ImageDockerBuild `protobuf:"bytes,4,opt,name=docker_build,json=dockerBuild,proto3,oneof"`
}

func (*ThunkImage_Ref) isThunkImage_Image() {}

func (*ThunkImage_Thunk) isThunkImage_Image() {}

func (*ThunkImage_Archive) isThunkImage_Image() {}

func (*ThunkImage_DockerBuild) isThunkImage_Image() {}

type ImageRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform *Platform `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	// Types that are assignable to Source:
	//
	//	*ImageRef_Repository
	//	*ImageRef_File
	//	*ImageRef_Addr
	Source isImageRef_Source `protobuf_oneof:"source"`
	Tag    *string           `protobuf:"bytes,4,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	Digest *string           `protobuf:"bytes,5,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
}

func (x *ImageRef) Reset() {
	*x = ImageRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRef) ProtoMessage() {}

func (x *ImageRef) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRef.ProtoReflect.Descriptor instead.
func (*ImageRef) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{6}
}

func (x *ImageRef) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (m *ImageRef) GetSource() isImageRef_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (x *ImageRef) GetRepository() string {
	if x, ok := x.GetSource().(*ImageRef_Repository); ok {
		return x.Repository
	}
	return ""
}

// Deprecated: Do not use.
func (x *ImageRef) GetFile() *ThunkPath {
	if x, ok := x.GetSource().(*ImageRef_File); ok {
		return x.File
	}
	return nil
}

func (x *ImageRef) GetAddr() *ThunkAddr {
	if x, ok := x.GetSource().(*ImageRef_Addr); ok {
		return x.Addr
	}
	return nil
}

func (x *ImageRef) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *ImageRef) GetDigest() string {
	if x != nil && x.Digest != nil {
		return *x.Digest
	}
	return ""
}

type isImageRef_Source interface {
	isImageRef_Source()
}

type ImageRef_Repository struct {
	Repository string `protobuf:"bytes,2,opt,name=repository,proto3,oneof"`
}

type ImageRef_File struct {
	// Deprecated: Do not use.
	File *ThunkPath `protobuf:"bytes,3,opt,name=file,proto3,oneof"`
}

type ImageRef_Addr struct {
	Addr *ThunkAddr `protobuf:"bytes,6,opt,name=addr,proto3,oneof"`
}

func (*ImageRef_Repository) isImageRef_Source() {}

func (*ImageRef_File) isImageRef_Source() {}

func (*ImageRef_Addr) isImageRef_Source() {}

type ImageArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform *Platform  `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	File     *ThunkPath `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Tag      *string    `protobuf:"bytes,3,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
}

func (x *ImageArchive) Reset() {
	*x = ImageArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageArchive) ProtoMessage() {}

func (x *ImageArchive) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageArchive.ProtoReflect.Descriptor instead.
func (*ImageArchive) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{7}
}

func (x *ImageArchive) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *ImageArchive) GetFile() *ThunkPath {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ImageArchive) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

type ImageDockerBuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform   *Platform        `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Context    *ImageBuildInput `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Dockerfile *string          `protobuf:"bytes,3,opt,name=dockerfile,proto3,oneof" json:"dockerfile,omitempty"`
	Target     *string          `protobuf:"bytes,4,opt,name=target,proto3,oneof" json:"target,omitempty"`
	Args       []*BuildArg      `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *ImageDockerBuild) Reset() {
	*x = ImageDockerBuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageDockerBuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDockerBuild) ProtoMessage() {}

func (x *ImageDockerBuild) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDockerBuild.ProtoReflect.Descriptor instead.
func (*ImageDockerBuild) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{8}
}

func (x *ImageDockerBuild) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *ImageDockerBuild) GetContext() *ImageBuildInput {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ImageDockerBuild) GetDockerfile() string {
	if x != nil && x.Dockerfile != nil {
		return *x.Dockerfile
	}
	return ""
}

func (x *ImageDockerBuild) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *ImageDockerBuild) GetArgs() []*BuildArg {
	if x != nil {
		return x.Args
	}
	return nil
}

type ImageBuildInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Input:
	//
	//	*ImageBuildInput_Thunk
	//	*ImageBuildInput_Host
	//	*ImageBuildInput_Logical
	Input isImageBuildInput_Input `protobuf_oneof:"input"`
}

func (x *ImageBuildInput) Reset() {
	*x = ImageBuildInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageBuildInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBuildInput) ProtoMessage() {}

func (x *ImageBuildInput) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBuildInput.ProtoReflect.Descriptor instead.
func (*ImageBuildInput) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{9}
}

func (m *ImageBuildInput) GetInput() isImageBuildInput_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (x *ImageBuildInput) GetThunk() *ThunkPath {
	if x, ok := x.GetInput().(*ImageBuildInput_Thunk); ok {
		return x.Thunk
	}
	return nil
}

func (x *ImageBuildInput) GetHost() *HostPath {
	if x, ok := x.GetInput().(*ImageBuildInput_Host); ok {
		return x.Host
	}
	return nil
}

func (x *ImageBuildInput) GetLogical() *LogicalPath {
	if x, ok := x.GetInput().(*ImageBuildInput_Logical); ok {
		return x.Logical
	}
	return nil
}

type isImageBuildInput_Input interface {
	isImageBuildInput_Input()
}

type ImageBuildInput_Thunk struct {
	Thunk *ThunkPath `protobuf:"bytes,1,opt,name=thunk,proto3,oneof"`
}

type ImageBuildInput_Host struct {
	Host *HostPath `protobuf:"bytes,2,opt,name=host,proto3,oneof"`
}

type ImageBuildInput_Logical struct {
	Logical *LogicalPath `protobuf:"bytes,3,opt,name=logical,proto3,oneof"`
}

func (*ImageBuildInput_Thunk) isImageBuildInput_Input() {}

func (*ImageBuildInput_Host) isImageBuildInput_Input() {}

func (*ImageBuildInput_Logical) isImageBuildInput_Input() {}

type BuildArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BuildArg) Reset() {
	*x = BuildArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildArg) ProtoMessage() {}

func (x *BuildArg) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildArg.ProtoReflect.Descriptor instead.
func (*BuildArg) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{10}
}

func (x *BuildArg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildArg) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Platform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Os   string `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch string `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
}

func (x *Platform) Reset() {
	*x = Platform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{11}
}

func (x *Platform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Platform) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type ThunkDir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Dir:
	//
	//	*ThunkDir_Local
	//	*ThunkDir_Thunk
	//	*ThunkDir_Host
	Dir isThunkDir_Dir `protobuf_oneof:"dir"`
}

func (x *ThunkDir) Reset() {
	*x = ThunkDir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThunkDir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThunkDir) ProtoMessage() {}

func (x *ThunkDir) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThunkDir.ProtoReflect.Descriptor instead.
func (*ThunkDir) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{12}
}

func (m *ThunkDir) GetDir() isThunkDir_Dir {
	if m != nil {
		return m.Dir
	}
	return nil
}

func (x *ThunkDir) GetLocal() *DirPath {
	if x, ok := x.GetDir().(*ThunkDir_Local); ok {
		return x.Local
	}
	return nil
}

func (x *ThunkDir) GetThunk() *ThunkPath {
	if x, ok := x.GetDir().(*ThunkDir_Thunk); ok {
		return x.Thunk
	}
	return nil
}

func (x *ThunkDir) GetHost() *HostPath {
	if x, ok := x.GetDir().(*ThunkDir_Host); ok {
		return x.Host
	}
	return nil
}

type isThunkDir_Dir interface {
	isThunkDir_Dir()
}

type ThunkDir_Local struct {
	Local *DirPath `protobuf:"bytes,12,opt,name=local,proto3,oneof"`
}

type ThunkDir_Thunk struct {
	Thunk *ThunkPath `protobuf:"bytes,13,opt,name=thunk,proto3,oneof"`
}

type ThunkDir_Host struct {
	Host *HostPath `protobuf:"bytes,14,opt,name=host,proto3,oneof"`
}

func (*ThunkDir_Local) isThunkDir_Dir() {}

func (*ThunkDir_Thunk) isThunkDir_Dir() {}

func (*ThunkDir_Host) isThunkDir_Dir() {}

type ThunkMountSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Source:
	//
	//	*ThunkMountSource_Thunk
	//	*ThunkMountSource_Host
	//	*ThunkMountSource_Logical
	//	*ThunkMountSource_Cache
	//	*ThunkMountSource_Secret
	Source isThunkMountSource_Source `protobuf_oneof:"source"`
}

func (x *ThunkMountSource) Reset() {
	*x = ThunkMountSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThunkMountSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThunkMountSource) ProtoMessage() {}

func (x *ThunkMountSource) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThunkMountSource.ProtoReflect.Descriptor instead.
func (*ThunkMountSource) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{13}
}

func (m *ThunkMountSource) GetSource() isThunkMountSource_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (x *ThunkMountSource) GetThunk() *ThunkPath {
	if x, ok := x.GetSource().(*ThunkMountSource_Thunk); ok {
		return x.Thunk
	}
	return nil
}

func (x *ThunkMountSource) GetHost() *HostPath {
	if x, ok := x.GetSource().(*ThunkMountSource_Host); ok {
		return x.Host
	}
	return nil
}

func (x *ThunkMountSource) GetLogical() *LogicalPath {
	if x, ok := x.GetSource().(*ThunkMountSource_Logical); ok {
		return x.Logical
	}
	return nil
}

func (x *ThunkMountSource) GetCache() *CachePath {
	if x, ok := x.GetSource().(*ThunkMountSource_Cache); ok {
		return x.Cache
	}
	return nil
}

func (x *ThunkMountSource) GetSecret() *Secret {
	if x, ok := x.GetSource().(*ThunkMountSource_Secret); ok {
		return x.Secret
	}
	return nil
}

type isThunkMountSource_Source interface {
	isThunkMountSource_Source()
}

type ThunkMountSource_Thunk struct {
	Thunk *ThunkPath `protobuf:"bytes,1,opt,name=thunk,proto3,oneof"`
}

type ThunkMountSource_Host struct {
	Host *HostPath `protobuf:"bytes,2,opt,name=host,proto3,oneof"`
}

type ThunkMountSource_Logical struct {
	Logical *LogicalPath `protobuf:"bytes,3,opt,name=logical,proto3,oneof"`
}

type ThunkMountSource_Cache struct {
	Cache *CachePath `protobuf:"bytes,4,opt,name=cache,proto3,oneof"`
}

type ThunkMountSource_Secret struct {
	Secret *Secret `protobuf:"bytes,5,opt,name=secret,proto3,oneof"`
}

func (*ThunkMountSource_Thunk) isThunkMountSource_Source() {}

func (*ThunkMountSource_Host) isThunkMountSource_Source() {}

func (*ThunkMountSource_Logical) isThunkMountSource_Source() {}

func (*ThunkMountSource_Cache) isThunkMountSource_Source() {}

func (*ThunkMountSource_Secret) isThunkMountSource_Source() {}

type ThunkMount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source *ThunkMountSource `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target *FilesystemPath   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *ThunkMount) Reset() {
	*x = ThunkMount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThunkMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThunkMount) ProtoMessage() {}

func (x *ThunkMount) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThunkMount.ProtoReflect.Descriptor instead.
func (*ThunkMount) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{14}
}

func (x *ThunkMount) GetSource() *ThunkMountSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ThunkMount) GetTarget() *FilesystemPath {
	if x != nil {
		return x.Target
	}
	return nil
}

type Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Array) Reset() {
	*x = Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Array) ProtoMessage() {}

func (x *Array) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Array.ProtoReflect.Descriptor instead.
func (*Array) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{15}
}

func (x *Array) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bindings []*Binding `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{16}
}

func (x *Object) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type Binding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Value  *Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Binding) Reset() {
	*x = Binding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{17}
}

func (x *Binding) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Binding) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Null struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Null) Reset() {
	*x = Null{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{18}
}

type Bool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Bool) Reset() {
	*x = Bool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bool) ProtoMessage() {}

func (x *Bool) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bool.ProtoReflect.Descriptor instead.
func (*Bool) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{19}
}

func (x *Bool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type Int struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Int) Reset() {
	*x = Int{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int) ProtoMessage() {}

func (x *Int) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int.ProtoReflect.Descriptor instead.
func (*Int) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{20}
}

func (x *Int) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *String) Reset() {
	*x = String{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{21}
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CachePath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path *FilesystemPath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *CachePath) Reset() {
	*x = CachePath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CachePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachePath) ProtoMessage() {}

func (x *CachePath) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachePath.ProtoReflect.Descriptor instead.
func (*CachePath) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{22}
}

func (x *CachePath) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CachePath) GetPath() *FilesystemPath {
	if x != nil {
		return x.Path
	}
	return nil
}

type Secret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Secret) Reset() {
	*x = Secret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{23}
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CommandPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CommandPath) Reset() {
	*x = CommandPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandPath) ProtoMessage() {}

func (x *CommandPath) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandPath.ProtoReflect.Descriptor instead.
func (*CommandPath) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{24}
}

func (x *CommandPath) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FilePath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *FilePath) Reset() {
	*x = FilePath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePath) ProtoMessage() {}

func (x *FilePath) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePath.ProtoReflect.Descriptor instead.
func (*FilePath) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{25}
}

func (x *FilePath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DirPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *DirPath) Reset() {
	*x = DirPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirPath) ProtoMessage() {}

func (x *DirPath) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirPath.ProtoReflect.Descriptor instead.
func (*DirPath) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{26}
}

func (x *DirPath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FilesystemPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Path:
	//
	//	*FilesystemPath_File
	//	*FilesystemPath_Dir
	Path isFilesystemPath_Path `protobuf_oneof:"path"`
}

func (x *FilesystemPath) Reset() {
	*x = FilesystemPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilesystemPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemPath) ProtoMessage() {}

func (x *FilesystemPath) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemPath.ProtoReflect.Descriptor instead.
func (*FilesystemPath) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{27}
}

func (m *FilesystemPath) GetPath() isFilesystemPath_Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (x *FilesystemPath) GetFile() *FilePath {
	if x, ok := x.GetPath().(*FilesystemPath_File); ok {
		return x.File
	}
	return nil
}

func (x *FilesystemPath) GetDir() *DirPath {
	if x, ok := x.GetPath().(*FilesystemPath_Dir); ok {
		return x.Dir
	}
	return nil
}

type isFilesystemPath_Path interface {
	isFilesystemPath_Path()
}

type FilesystemPath_File struct {
	File *FilePath `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type FilesystemPath_Dir struct {
	Dir *DirPath `protobuf:"bytes,2,opt,name=dir,proto3,oneof"`
}

func (*FilesystemPath_File) isFilesystemPath_Path() {}

func (*FilesystemPath_Dir) isFilesystemPath_Path() {}

type ThunkPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thunk *Thunk          `protobuf:"bytes,1,opt,name=thunk,proto3" json:"thunk,omitempty"`
	Path  *FilesystemPath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ThunkPath) Reset() {
	*x = ThunkPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThunkPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThunkPath) ProtoMessage() {}

func (x *ThunkPath) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThunkPath.ProtoReflect.Descriptor instead.
func (*ThunkPath) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{28}
}

func (x *ThunkPath) GetThunk() *Thunk {
	if x != nil {
		return x.Thunk
	}
	return nil
}

func (x *ThunkPath) GetPath() *FilesystemPath {
	if x != nil {
		return x.Path
	}
	return nil
}

type HostPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context string          `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Path    *FilesystemPath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *HostPath) Reset() {
	*x = HostPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostPath) ProtoMessage() {}

func (x *HostPath) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostPath.ProtoReflect.Descriptor instead.
func (*HostPath) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{29}
}

func (x *HostPath) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *HostPath) GetPath() *FilesystemPath {
	if x != nil {
		return x.Path
	}
	return nil
}

type LogicalPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Path:
	//
	//	*LogicalPath_File_
	//	*LogicalPath_Dir_
	Path isLogicalPath_Path `protobuf_oneof:"path"`
}

func (x *LogicalPath) Reset() {
	*x = LogicalPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicalPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalPath) ProtoMessage() {}

func (x *LogicalPath) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalPath.ProtoReflect.Descriptor instead.
func (*LogicalPath) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{30}
}

func (m *LogicalPath) GetPath() isLogicalPath_Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (x *LogicalPath) GetFile() *LogicalPath_File {
	if x, ok := x.GetPath().(*LogicalPath_File_); ok {
		return x.File
	}
	return nil
}

func (x *LogicalPath) GetDir() *LogicalPath_Dir {
	if x, ok := x.GetPath().(*LogicalPath_Dir_); ok {
		return x.Dir
	}
	return nil
}

type isLogicalPath_Path interface {
	isLogicalPath_Path()
}

type LogicalPath_File_ struct {
	File *LogicalPath_File `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type LogicalPath_Dir_ struct {
	Dir *LogicalPath_Dir `protobuf:"bytes,2,opt,name=dir,proto3,oneof"`
}

func (*LogicalPath_File_) isLogicalPath_Path() {}

func (*LogicalPath_Dir_) isLogicalPath_Path() {}

type LogicalPath_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *LogicalPath_File) Reset() {
	*x = LogicalPath_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicalPath_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalPath_File) ProtoMessage() {}

func (x *LogicalPath_File) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalPath_File.ProtoReflect.Descriptor instead.
func (*LogicalPath_File) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{30, 0}
}

func (x *LogicalPath_File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogicalPath_File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type LogicalPath_Dir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Entries []*LogicalPath `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *LogicalPath_Dir) Reset() {
	*x = LogicalPath_Dir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bass_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicalPath_Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalPath_Dir) ProtoMessage() {}

func (x *LogicalPath_Dir) ProtoReflect() protoreflect.Message {
	mi := &file_bass_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalPath_Dir.ProtoReflect.Descriptor instead.
func (*LogicalPath_Dir) Descriptor() ([]byte, []int) {
	return file_bass_proto_rawDescGZIP(), []int{30, 1}
}

func (x *LogicalPath_Dir) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogicalPath_Dir) GetEntries() []*LogicalPath {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_bass_proto protoreflect.FileDescriptor

var file_bass_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x61,
	0x73, 0x73, 0x22, 0xc5, 0x05, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x04,
	0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x61, 0x73,
	0x73, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x12, 0x20,
	0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62,
	0x61, 0x73, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c,
	0x12, 0x1d, 0x0a, 0x03, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x62, 0x61, 0x73, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12,
	0x26, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12,
	0x23, 0x0a, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x48, 0x00, 0x52, 0x05, 0x61,
	0x72, 0x72, 0x61, 0x79, 0x12, 0x26, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x23, 0x0a, 0x05,
	0x74, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x61,
	0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x74, 0x68, 0x75, 0x6e,
	0x6b, 0x12, 0x36, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2d, 0x0a, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62,
	0x61, 0x73, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2a, 0x0a, 0x08, 0x64, 0x69, 0x72, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x61, 0x73,
	0x73, 0x2e, 0x44, 0x69, 0x72, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x07, 0x64, 0x69, 0x72,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x2d, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x48,
	0x6f, 0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x30, 0x0a, 0x0a, 0x74, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54,
	0x68, 0x75, 0x6e, 0x6b, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x09, 0x74, 0x68, 0x75, 0x6e,
	0x6b, 0x50, 0x61, 0x74, 0x68, 0x12, 0x36, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x61,
	0x73, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00,
	0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x30, 0x0a,
	0x0a, 0x74, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x41, 0x64,
	0x64, 0x72, 0x48, 0x00, 0x52, 0x09, 0x74, 0x68, 0x75, 0x6e, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x30, 0x0a, 0x0a, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x09, 0x63, 0x61, 0x63, 0x68, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xec, 0x02, 0x0a, 0x05, 0x54,
	0x68, 0x75, 0x6e, 0x6b, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x69, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x74, 0x64,
	0x69, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x12, 0x1f, 0x0a, 0x03,
	0x65, 0x6e, 0x76, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x61, 0x73, 0x73,
	0x2e, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x20, 0x0a,
	0x03, 0x64, 0x69, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73,
	0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x69, 0x72, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12,
	0x28, 0x0a, 0x06, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x4d, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x06, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x61, 0x73, 0x73,
	0x2e, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x12, 0x25, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x50, 0x6f, 0x72, 0x74,
	0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x03, 0x74, 0x6c, 0x73, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e,
	0x6b, 0x54, 0x4c, 0x53, 0x52, 0x03, 0x74, 0x6c, 0x73, 0x22, 0x5a, 0x0a, 0x09, 0x54, 0x68, 0x75,
	0x6e, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x12, 0x21, 0x0a, 0x05, 0x74, 0x68, 0x75, 0x6e, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75,
	0x6e, 0x6b, 0x52, 0x05, 0x74, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x33, 0x0a, 0x09, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x50, 0x0a, 0x08, 0x54, 0x68,
	0x75, 0x6e, 0x6b, 0x54, 0x4c, 0x53, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0xcb, 0x01, 0x0a,
	0x0a, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x72,
	0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x48, 0x00, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12,
	0x23, 0x0a, 0x05, 0x74, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x74,
	0x68, 0x75, 0x6e, 0x6b, 0x12, 0x2e, 0x0a, 0x07, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x48, 0x00, 0x52, 0x07, 0x61, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x73,
	0x73, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x42, 0x07, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0xfb, 0x01, 0x0a, 0x08, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x73,
	0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x12, 0x20, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b,
	0x50, 0x61, 0x74, 0x68, 0x42, 0x02, 0x18, 0x01, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x25, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x48,
	0x00, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x15, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x03, 0x74, 0x61, 0x67, 0x88, 0x01, 0x01, 0x12, 0x1b,
	0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02,
	0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x74, 0x61, 0x67, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x7e, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73,
	0x73, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x23, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x50,
	0x61, 0x74, 0x68, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x74, 0x61, 0x67, 0x88, 0x01, 0x01,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x74, 0x61, 0x67, 0x22, 0xef, 0x01, 0x0a, 0x10, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x2a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x61, 0x73,
	0x73, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x23, 0x0a, 0x0a, 0x64, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0a, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x1b, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73,
	0x73, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x72, 0x67, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x98, 0x01, 0x0a, 0x0f, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x27,
	0x0a, 0x05, 0x74, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00,
	0x52, 0x05, 0x74, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x48, 0x6f, 0x73,
	0x74, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x2d, 0x0a,
	0x07, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74,
	0x68, 0x48, 0x00, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x42, 0x07, 0x0a, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x34, 0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x72,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2e, 0x0a, 0x08, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x22, 0x87, 0x01, 0x0a, 0x08,
	0x54, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x69, 0x72, 0x12, 0x25, 0x0a, 0x05, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x44,
	0x69, 0x72, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x12,
	0x27, 0x0a, 0x05, 0x74, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x50, 0x61, 0x74, 0x68, 0x48,
	0x00, 0x52, 0x05, 0x74, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x42, 0x05,
	0x0a, 0x03, 0x64, 0x69, 0x72, 0x22, 0xeb, 0x01, 0x0a, 0x10, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x4d,
	0x6f, 0x75, 0x6e, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x74, 0x68,
	0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x73, 0x73,
	0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x05, 0x74, 0x68,
	0x75, 0x6e, 0x6b, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x48, 0x00, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x6c, 0x6f, 0x67,
	0x69, 0x63, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x61, 0x73,
	0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52,
	0x07, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x27, 0x0a, 0x05, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x05, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x22, 0x6a, 0x0a, 0x0a, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x4d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x4d, 0x6f,
	0x75, 0x6e, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x2c, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x50, 0x61, 0x74, 0x68, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22,
	0x2c, 0x0a, 0x05, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x23, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x33, 0x0a,
	0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x62, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x61, 0x73, 0x73,
	0x2e, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x73, 0x22, 0x44, 0x0a, 0x07, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x06, 0x0a, 0x04, 0x4e, 0x75, 0x6c, 0x6c,
	0x22, 0x1c, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1b,
	0x0a, 0x03, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x06, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x45, 0x0a, 0x09, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x74, 0x68, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x1c, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x21, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x1e, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0x1d, 0x0a, 0x07, 0x44, 0x69, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x61, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x64, 0x69,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x44,
	0x69, 0x72, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x03, 0x64, 0x69, 0x72, 0x42, 0x06, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x58, 0x0a, 0x09, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x21, 0x0a, 0x05, 0x74, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x54, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x05,
	0x74, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x28, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x74, 0x68, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22,
	0x4e, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x61, 0x73, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x74, 0x68, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22,
	0xec, 0x01, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x2c, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x62, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x29, 0x0a,
	0x03, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x61, 0x73,
	0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x2e, 0x44, 0x69,
	0x72, 0x48, 0x00, 0x52, 0x03, 0x64, 0x69, 0x72, 0x1a, 0x34, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x46,
	0x0a, 0x03, 0x44, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x61, 0x73,
	0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x52, 0x07, 0x65,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x42, 0x0b,
	0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_bass_proto_rawDescOnce sync.Once
	file_bass_proto_rawDescData = file_bass_proto_rawDesc
)

func file_bass_proto_rawDescGZIP() []byte {
	file_bass_proto_rawDescOnce.Do(func() {
		file_bass_proto_rawDescData = protoimpl.X.CompressGZIP(file_bass_proto_rawDescData)
	})
	return file_bass_proto_rawDescData
}

var file_bass_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_bass_proto_goTypes = []interface{}{
	(*Value)(nil),            // 0: bass.Value
	(*Thunk)(nil),            // 1: bass.Thunk
	(*ThunkAddr)(nil),        // 2: bass.ThunkAddr
	(*ThunkPort)(nil),        // 3: bass.ThunkPort
	(*ThunkTLS)(nil),         // 4: bass.ThunkTLS
	(*ThunkImage)(nil),       // 5: bass.ThunkImage
	(*ImageRef)(nil),         // 6: bass.ImageRef
	(*ImageArchive)(nil),     // 7: bass.ImageArchive
	(*ImageDockerBuild)(nil), // 8: bass.ImageDockerBuild
	(*ImageBuildInput)(nil),  // 9: bass.ImageBuildInput
	(*BuildArg)(nil),         // 10: bass.BuildArg
	(*Platform)(nil),         // 11: bass.Platform
	(*ThunkDir)(nil),         // 12: bass.ThunkDir
	(*ThunkMountSource)(nil), // 13: bass.ThunkMountSource
	(*ThunkMount)(nil),       // 14: bass.ThunkMount
	(*Array)(nil),            // 15: bass.Array
	(*Object)(nil),           // 16: bass.Object
	(*Binding)(nil),          // 17: bass.Binding
	(*Null)(nil),             // 18: bass.Null
	(*Bool)(nil),             // 19: bass.Bool
	(*Int)(nil),              // 20: bass.Int
	(*String)(nil),           // 21: bass.String
	(*CachePath)(nil),        // 22: bass.CachePath
	(*Secret)(nil),           // 23: bass.Secret
	(*CommandPath)(nil),      // 24: bass.CommandPath
	(*FilePath)(nil),         // 25: bass.FilePath
	(*DirPath)(nil),          // 26: bass.DirPath
	(*FilesystemPath)(nil),   // 27: bass.FilesystemPath
	(*ThunkPath)(nil),        // 28: bass.ThunkPath
	(*HostPath)(nil),         // 29: bass.HostPath
	(*LogicalPath)(nil),      // 30: bass.LogicalPath
	(*LogicalPath_File)(nil), // 31: bass.LogicalPath.File
	(*LogicalPath_Dir)(nil),  // 32: bass.LogicalPath.Dir
}
var file_bass_proto_depIdxs = []int32{
	18, // 0: bass.Value.null:type_name -> bass.Null
	19, // 1: bass.Value.bool:type_name -> bass.Bool
	20, // 2: bass.Value.int:type_name -> bass.Int
	21, // 3: bass.Value.string:type_name -> bass.String
	23, // 4: bass.Value.secret:type_name -> bass.Secret
	15, // 5: bass.Value.array:type_name -> bass.Array
	16, // 6: bass.Value.object:type_name -> bass.Object
	1,  // 7: bass.Value.thunk:type_name -> bass.Thunk
	24, // 8: bass.Value.command_path:type_name -> bass.CommandPath
	25, // 9: bass.Value.file_path:type_name -> bass.FilePath
	26, // 10: bass.Value.dir_path:type_name -> bass.DirPath
	29, // 11: bass.Value.host_path:type_name -> bass.HostPath
	28, // 12: bass.Value.thunk_path:type_name -> bass.ThunkPath
	30, // 13: bass.Value.logical_path:type_name -> bass.LogicalPath
	2,  // 14: bass.Value.thunk_addr:type_name -> bass.ThunkAddr
	22, // 15: bass.Value.cache_path:type_name -> bass.CachePath
	5,  // 16: bass.Thunk.image:type_name -> bass.ThunkImage
	0,  // 17: bass.Thunk.args:type_name -> bass.Value
	0,  // 18: bass.Thunk.stdin:type_name -> bass.Value
	17, // 19: bass.Thunk.env:type_name -> bass.Binding
	12, // 20: bass.Thunk.dir:type_name -> bass.ThunkDir
	14, // 21: bass.Thunk.mounts:type_name -> bass.ThunkMount
	17, // 22: bass.Thunk.labels:type_name -> bass.Binding
	3,  // 23: bass.Thunk.ports:type_name -> bass.ThunkPort
	4,  // 24: bass.Thunk.tls:type_name -> bass.ThunkTLS
	1,  // 25: bass.ThunkAddr.thunk:type_name -> bass.Thunk
	25, // 26: bass.ThunkTLS.cert:type_name -> bass.FilePath
	25, // 27: bass.ThunkTLS.key:type_name -> bass.FilePath
	6,  // 28: bass.ThunkImage.ref:type_name -> bass.ImageRef
	1,  // 29: bass.ThunkImage.thunk:type_name -> bass.Thunk
	7,  // 30: bass.ThunkImage.archive:type_name -> bass.ImageArchive
	8,  // 31: bass.ThunkImage.docker_build:type_name -> bass.ImageDockerBuild
	11, // 32: bass.ImageRef.platform:type_name -> bass.Platform
	28, // 33: bass.ImageRef.file:type_name -> bass.ThunkPath
	2,  // 34: bass.ImageRef.addr:type_name -> bass.ThunkAddr
	11, // 35: bass.ImageArchive.platform:type_name -> bass.Platform
	28, // 36: bass.ImageArchive.file:type_name -> bass.ThunkPath
	11, // 37: bass.ImageDockerBuild.platform:type_name -> bass.Platform
	9,  // 38: bass.ImageDockerBuild.context:type_name -> bass.ImageBuildInput
	10, // 39: bass.ImageDockerBuild.args:type_name -> bass.BuildArg
	28, // 40: bass.ImageBuildInput.thunk:type_name -> bass.ThunkPath
	29, // 41: bass.ImageBuildInput.host:type_name -> bass.HostPath
	30, // 42: bass.ImageBuildInput.logical:type_name -> bass.LogicalPath
	26, // 43: bass.ThunkDir.local:type_name -> bass.DirPath
	28, // 44: bass.ThunkDir.thunk:type_name -> bass.ThunkPath
	29, // 45: bass.ThunkDir.host:type_name -> bass.HostPath
	28, // 46: bass.ThunkMountSource.thunk:type_name -> bass.ThunkPath
	29, // 47: bass.ThunkMountSource.host:type_name -> bass.HostPath
	30, // 48: bass.ThunkMountSource.logical:type_name -> bass.LogicalPath
	22, // 49: bass.ThunkMountSource.cache:type_name -> bass.CachePath
	23, // 50: bass.ThunkMountSource.secret:type_name -> bass.Secret
	13, // 51: bass.ThunkMount.source:type_name -> bass.ThunkMountSource
	27, // 52: bass.ThunkMount.target:type_name -> bass.FilesystemPath
	0,  // 53: bass.Array.values:type_name -> bass.Value
	17, // 54: bass.Object.bindings:type_name -> bass.Binding
	0,  // 55: bass.Binding.value:type_name -> bass.Value
	27, // 56: bass.CachePath.path:type_name -> bass.FilesystemPath
	25, // 57: bass.FilesystemPath.file:type_name -> bass.FilePath
	26, // 58: bass.FilesystemPath.dir:type_name -> bass.DirPath
	1,  // 59: bass.ThunkPath.thunk:type_name -> bass.Thunk
	27, // 60: bass.ThunkPath.path:type_name -> bass.FilesystemPath
	27, // 61: bass.HostPath.path:type_name -> bass.FilesystemPath
	31, // 62: bass.LogicalPath.file:type_name -> bass.LogicalPath.File
	32, // 63: bass.LogicalPath.dir:type_name -> bass.LogicalPath.Dir
	30, // 64: bass.LogicalPath.Dir.entries:type_name -> bass.LogicalPath
	65, // [65:65] is the sub-list for method output_type
	65, // [65:65] is the sub-list for method input_type
	65, // [65:65] is the sub-list for extension type_name
	65, // [65:65] is the sub-list for extension extendee
	0,  // [0:65] is the sub-list for field type_name
}

func init() { file_bass_proto_init() }
func file_bass_proto_init() {
	if File_bass_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bass_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Thunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThunkAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThunkPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThunkTLS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThunkImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageDockerBuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageBuildInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Platform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThunkDir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThunkMountSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThunkMount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Binding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Null); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*String); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CachePath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilesystemPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThunkPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicalPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicalPath_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bass_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicalPath_Dir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bass_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Value_Null)(nil),
		(*Value_Bool)(nil),
		(*Value_Int)(nil),
		(*Value_String_)(nil),
		(*Value_Secret)(nil),
		(*Value_Array)(nil),
		(*Value_Object)(nil),
		(*Value_Thunk)(nil),
		(*Value_CommandPath)(nil),
		(*Value_FilePath)(nil),
		(*Value_DirPath)(nil),
		(*Value_HostPath)(nil),
		(*Value_ThunkPath)(nil),
		(*Value_LogicalPath)(nil),
		(*Value_ThunkAddr)(nil),
		(*Value_CachePath)(nil),
	}
	file_bass_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ThunkImage_Ref)(nil),
		(*ThunkImage_Thunk)(nil),
		(*ThunkImage_Archive)(nil),
		(*ThunkImage_DockerBuild)(nil),
	}
	file_bass_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*ImageRef_Repository)(nil),
		(*ImageRef_File)(nil),
		(*ImageRef_Addr)(nil),
	}
	file_bass_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_bass_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_bass_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*ImageBuildInput_Thunk)(nil),
		(*ImageBuildInput_Host)(nil),
		(*ImageBuildInput_Logical)(nil),
	}
	file_bass_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ThunkDir_Local)(nil),
		(*ThunkDir_Thunk)(nil),
		(*ThunkDir_Host)(nil),
	}
	file_bass_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*ThunkMountSource_Thunk)(nil),
		(*ThunkMountSource_Host)(nil),
		(*ThunkMountSource_Logical)(nil),
		(*ThunkMountSource_Cache)(nil),
		(*ThunkMountSource_Secret)(nil),
	}
	file_bass_proto_msgTypes[27].OneofWrappers = []interface{}{
		(*FilesystemPath_File)(nil),
		(*FilesystemPath_Dir)(nil),
	}
	file_bass_proto_msgTypes[30].OneofWrappers = []interface{}{
		(*LogicalPath_File_)(nil),
		(*LogicalPath_Dir_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bass_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bass_proto_goTypes,
		DependencyIndexes: file_bass_proto_depIdxs,
		MessageInfos:      file_bass_proto_msgTypes,
	}.Build()
	File_bass_proto = out.File
	file_bass_proto_rawDesc = nil
	file_bass_proto_goTypes = nil
	file_bass_proto_depIdxs = nil
}
